version: '3.8'

services:
  frontend-dev:
    container_name: nnak-frontend-dev-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3020:3000"  # Maps VPS port 3020 to internal container port 3000
    environment:
      - NODE_ENV=development
    restart: always