#!/usr/bin/env bash
#
# Zero-downtime deploy for the NNAK frontend.
#
# The old deploy stopped the container and only then built the new image, so
# the site was down for the whole build. This one never stops what is serving
# traffic until the replacement has proved it can answer requests:
#
#   1. build the image           — old container still serving
#   2. start the idle colour on its own port
#   3. poll that port until it answers
#   4. repoint the nginx upstream and reload (graceful: in-flight requests
#      finish on the old worker)
#   5. only then stop the previous colour
#
# If step 3 never succeeds the new container is torn down, nginx is left
# pointing at the old one, and the script exits non-zero — a failed deploy
# leaves the site up on the previous release.
#
# Must run as root: it reloads nginx.
#
# Configured entirely by environment variables so dev and production share
# this one script:
#
#   COMPOSE_FILE    compose file to use            (docker-compose.yml)
#   SERVICE         service name inside it         (app)
#   PROJECT         compose project name prefix    (nnak)
#   PORT_BLUE       host port for the blue slot    (3010)
#   PORT_GREEN      host port for the green slot   (3011)
#   UPSTREAM_FILE   nginx include holding the upstream block
#   UPSTREAM_NAME   upstream name the vhost proxies to
#   HEALTH_PATH     path to poll                   (/)
#   HEALTH_TIMEOUT  seconds to wait for health     (120)
#   DRAIN_SECONDS   grace before stopping the old  (5)
#
set -euo pipefail

COMPOSE_FILE="${COMPOSE_FILE:-docker-compose.yml}"
SERVICE="${SERVICE:-app}"
PROJECT="${PROJECT:-nnak}"
PORT_BLUE="${PORT_BLUE:-3010}"
PORT_GREEN="${PORT_GREEN:-3011}"
UPSTREAM_FILE="${UPSTREAM_FILE:-/etc/nginx/conf.d/nnak-upstream.conf}"
UPSTREAM_NAME="${UPSTREAM_NAME:-nnak_app}"
HEALTH_PATH="${HEALTH_PATH:-/}"
HEALTH_TIMEOUT="${HEALTH_TIMEOUT:-120}"
DRAIN_SECONDS="${DRAIN_SECONDS:-5}"

log() { echo "==> $*"; }

compose() { docker compose -f "$COMPOSE_FILE" "$@"; }
compose_for() {
  local colour="$1"; shift
  docker compose -p "${PROJECT}-${colour}" -f "$COMPOSE_FILE" "$@"
}

# A colour counts as running only if its container is actually up — a stale
# upstream pointing at a dead container must not be treated as live.
# `compose ps -q` lists running containers only, so a non-empty id means the
# colour is actually serving rather than merely defined.
colour_running() {
  [ -n "$(compose_for "$1" ps -q "$SERVICE" 2>/dev/null)" ]
}

# Which colour is serving? The upstream file is the source of truth; fall back
# to whichever container happens to be running.
current_colour() {
  if [ -f "$UPSTREAM_FILE" ]; then
    if grep -q ":${PORT_GREEN};" "$UPSTREAM_FILE" && colour_running green; then
      echo green; return
    fi
    if grep -q ":${PORT_BLUE};" "$UPSTREAM_FILE" && colour_running blue; then
      echo blue; return
    fi
  fi
  if colour_running blue; then echo blue; return; fi
  if colour_running green; then echo green; return; fi
  echo none
}

write_upstream() {
  local port="$1"
  cat > "$UPSTREAM_FILE" <<EOF
# Generated by scripts/deploy-blue-green.sh — do not edit by hand.
# Points at the colour currently serving traffic.
upstream ${UPSTREAM_NAME} {
    server 127.0.0.1:${port};
    keepalive 32;
}
EOF
}

ACTIVE="$(current_colour)"
if [ "$ACTIVE" = "green" ]; then
  IDLE=blue;  IDLE_PORT="$PORT_BLUE";  ACTIVE_PORT="$PORT_GREEN"
else
  IDLE=green; IDLE_PORT="$PORT_GREEN"; ACTIVE_PORT="$PORT_BLUE"
fi

log "Active colour: ${ACTIVE} (port ${ACTIVE_PORT}) → deploying ${IDLE} on ${IDLE_PORT}"

# ── 1. Build while the current release keeps serving ──────────────────
log "Building image (current release still serving)..."
compose build "$SERVICE"

# ── 2. Start the idle colour ──────────────────────────────────────────
log "Starting ${IDLE} container..."
APP_PORT="$IDLE_PORT" compose_for "$IDLE" up -d --force-recreate "$SERVICE"

# ── 3. Wait for it to answer ──────────────────────────────────────────
log "Waiting for ${IDLE} to respond on ${IDLE_PORT}${HEALTH_PATH} (timeout ${HEALTH_TIMEOUT}s)..."
HEALTHY=0
DEADLINE=$((SECONDS + HEALTH_TIMEOUT))
while [ "$SECONDS" -lt "$DEADLINE" ]; do
  # Anything under 500 counts: the app redirects / to the login route, and a
  # 3xx proves Next.js is up and routing.
  CODE="$(curl -s -o /dev/null -w '%{http_code}' --max-time 5 \
    "http://127.0.0.1:${IDLE_PORT}${HEALTH_PATH}" || echo 000)"
  if [ "$CODE" != "000" ] && [ "$CODE" -lt 500 ]; then
    log "    ${IDLE} answered HTTP ${CODE} — ready."
    HEALTHY=1
    break
  fi
  sleep 2
done

if [ "$HEALTHY" -ne 1 ]; then
  echo "::error:: ${IDLE} never became healthy — keeping ${ACTIVE} live."
  compose_for "$IDLE" logs --tail=50 "$SERVICE" || true
  compose_for "$IDLE" down --remove-orphans || true
  exit 1
fi

# ── 4. Switch nginx to the new colour ─────────────────────────────────
BACKUP=""
if [ -f "$UPSTREAM_FILE" ]; then
  BACKUP="${UPSTREAM_FILE}.bak"
  cp "$UPSTREAM_FILE" "$BACKUP"
fi

log "Repointing ${UPSTREAM_NAME} → 127.0.0.1:${IDLE_PORT}"
write_upstream "$IDLE_PORT"

if ! nginx -t; then
  echo "::error:: nginx config invalid after upstream switch — rolling back."
  [ -n "$BACKUP" ] && cp "$BACKUP" "$UPSTREAM_FILE"
  compose_for "$IDLE" down --remove-orphans || true
  exit 1
fi

# A reload finishes in-flight requests on the old workers, so no connection is
# dropped at the swap.
nginx -s reload
log "    nginx reloaded — traffic now on ${IDLE}."

# ── 5. Retire the previous colour ─────────────────────────────────────
if [ "$ACTIVE" != "none" ]; then
  log "Draining ${ACTIVE} for ${DRAIN_SECONDS}s before stopping it..."
  sleep "$DRAIN_SECONDS"
  compose_for "$ACTIVE" down --remove-orphans || true
  log "    ${ACTIVE} stopped."
else
  # First run after switching to blue/green: the pre-existing container still
  # runs under the default (directory-named) project and holds the old port.
  # Nothing points at it any more, so retire it.
  if [ -n "$(compose ps -q "$SERVICE" 2>/dev/null)" ]; then
    log "Retiring the pre-blue/green container from the default project..."
    sleep "$DRAIN_SECONDS"
    compose down --remove-orphans || true
  fi
fi

[ -n "$BACKUP" ] && rm -f "$BACKUP"

log "Deploy complete — live on ${IDLE} (port ${IDLE_PORT})."
